### ISSUE TITLE
Error following recent tweet

### ISSUE THREAD

**Issue by Dotnaught** [maxbbraun/trump2cash#44] opened 2017-03-07 05:41 UTC
TweepError: [{u'message': u'Status is over 140 characters.', u'code': 186}]
at execute (/usr/local/lib/python2.7/dist-packages/tweepy/binder.py:229)
at _call (/usr/local/lib/python2.7/dist-packages/tweepy/binder.py:245)
at update_status (/usr/local/lib/python2.7/dist-packages/tweepy/api.py:194)
at tweet (/home/czxm/trump2cash/twitter.py:89)
at twitter_callback (./main.py:24)
at handle_data (/home/czxm/trump2cash/twitter.py:276)
at process_queue (/home/czxm/trump2cash/twitter.py:219)

**Comment by maxbbraun** [comment] 2017-03-07 06:11
Duplicate of #43.

**Closed by maxbbraun** 2017-03-07 06:11 UTC
