### ISSUE TITLE
Robinhood API Integration - $0 fees

### ISSUE THREAD

**Issue by dskvr** [maxbbraun/trump2cash#39] opened 2017-02-24 23:42 UTC
The API has been reversed engineered (https://github.com/sanko/Robinhood) but it does appear that Robinhood has plans to release an API (https://support.robinhood.com/hc/en-us/articles/210216823-Robinhood-API-Integrations)

**Comment by maxbbraun** [comment] 2017-02-25 00:05
Duplicate of #22.

**Closed by maxbbraun** 2017-02-25 00:05 UTC

**Comment by WilliamJamesDalrympleWest** [comment] 2017-08-26 14:40
Is this intergrateable?
